### ISSUE TITLE
Make By default Route to a 404 page or Homepage.

### ISSUE THREAD

**Issue by 180896-cse** [ByteCodeLearners/official-site#109]
Write a Redirection of any page which is not in the list of Route  to the 404 page or Homepage
![Capture](https://user-images.githubusercontent.com/62785261/123152408-2f570080-d482-11eb-96dd-b8aa314ed04f.PNG)

**Comment by SourabhSaraswat-191939** [comment]
the page shown with the text "Route not found" in this screenshot is of the route not found page, but it is not styled yet.

**Comment by SourabhSaraswat-191939** [comment]
we will update it by today.

**Comment by SourabhSaraswat-191939** [comment]
Issue is solved now.
